export { default as EventDetails } from './EventDetails'
export { default as Event } from './Event'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'