export { default as EventDetails } from './EventDetails'
export { default as Events } from './Events'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'